### ISSUE TITLE
Fix problem with diff-ing long strings

### ISSUE THREAD

**Issue by srp33** [srp33/CodeBuddy#130]
Assignment 10, Exercise 2 on BIO 264.

Traceback (most recent call last):
  File "/app/RunCodeHandler.py", line 13, in post
    diff, passed, tests = check_exercise_output(exercise_details, text_output, image_output, tests)
  File "/app/helper.py", line 171, in check_exercise_output
    diff_output, passed = compare_outputs(exercise_details["expected_text_output"], actual_text, exercise_details["expected_image_output"], actual_image, exercise_details["output_type"])
  File "/app/helper.py", line 141, in compare_outputs
    diff_output, num_differences = diff_strings(expected_text, actual_text)
  File "/app/helper.py", line 210, in diff_strings
    for x in diff:
  File "/usr/local/lib/python3.9/difflib.py", line 912, in compare
    yield from g
  File "/usr/local/lib/python3.9/difflib.py", line 1025, in _fancy_replace
    yield from self._fancy_helper(a, best_i+1, ahi, b, best_j+1, bhi)
  File "/usr/local/lib/python3.9/difflib.py", line 1037, in _fancy_helper
    yield from g
  File "/usr/local/lib/python3.9/difflib.py", line 1025, in _fancy_replace
    yield from self._fancy_helper(a, best_i+1, ahi, b, best_j+1, bhi)
  File "/usr/local/lib/python3.9/difflib.py", line 1037, in _fancy_helper
    yield from g
  File "/usr/local/lib/python3.9/difflib.py", line 955, in _fancy_replace
    cruncher = SequenceMatcher(self.charjunk)
  File "/usr/local/lib/python3.9/difflib.py", line 214, in __init__
    self.set_seqs(a, b)
  File "/usr/local/lib/python3.9/difflib.py", line 226, in set_seqs
    self.set_seq2(b)
  File "/usr/local/lib/python3.9/difflib.py", line 280, in set_seq2
    self.__chain_b()
RecursionError: maximum recursion depth exceeded

Figure out whether the problem is the length of the strings being compared. Or whether it is that there are so many differences that the system cannot handle it. If it’s the latter, then write code that checks the ratio between the length of the expected output and the student’s output. If the ratio is too high or too low, don’t do a diff (as long as the expected output is above a minimum size).

Still necessary with Studio mode?

**Comment by srp33** [comment]
https://github.com/ace-diff/ace-diff
