### ISSUE TITLE
Consent forms page is not working quite right.

### ISSUE THREAD

**Issue by srp33** [srp33/CodeBuddy#135]
No consent forms show for me as an admin. It just says, "Consent forms for [course].” I guess that’s just because no students have signed it yet. Just add a message saying that no students have sign yet.

I haven’t been able to reproduce the error message that PJ was getting (see comment).

Traceback (most recent call last):
  File "/app/ConsentFormsHandler.py", line 22, in get
    self.render("consent_forms.html", page="consent_forms", result=None, registered_courses=registered_courses, user_info=self.get_user_info(), is_administrator=self.is_administrator(), is_instructor=self.is_instructor(), is_assistant=self.is_assistant())
  File "/home/codebuddy/.local/lib/python3.9/site-packages/tornado/web.py", line 856, in render
    html = self.render_string(template_name, **kwargs)
  File "/home/codebuddy/.local/lib/python3.9/site-packages/tornado/web.py", line 1005, in render_string
    return t.generate(**namespace)
  File "/home/codebuddy/.local/lib/python3.9/site-packages/tornado/template.py", line 361, in generate
    return execute()
  File "consent_forms_html.generated.py", line 165, in _tt_execute
    if course[1]["consent_text"] != '' and course[1]["consent_text"]:  # consent_forms.html:190
KeyError: 'consent_text'

**Comment by srp33** [comment]
Removed consent forms altogether, so this issue is no longer a concern.
